Repository FC-MINI-4/attendance-back, pull requests merged in 2023-08, with the labels that each got.

#81 refactor: "요청됨" -> 대기중 (#80)
  src/main/java/com/toy4/domain/schedule/RequestStatus.java
Labels: refactor

#83 fix: 프로필 이미지 파일 NPE (#82)
  src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java
Labels: fix

#85 fix: 연차 등록 신청 시 잔여 연차 수 감소 (#84)
  src/main/java/com/toy4/domain/dayOffHistory/service/DayOffHistoryMainService.java
Labels: fix

#93 개인정보 수정 관련 리팩토링 #87
  src/main/java/com/toy4/domain/department/type/DepartmentType.java
  src/main/java/com/toy4/domain/employee/controller/EmployeeAdminController.java
  src/main/java/com/toy4/domain/employee/controller/EmployeeInfoController.java
  src/main/java/com/toy4/domain/employee/domain/Employee.java
  src/main/java/com/toy4/domain/employee/dto/request/EmployeeInfoRequest.java
  src/main/java/com/toy4/domain/employee/dto/request/PersonalInfoRequest.java
  src/main/java/com/toy4/domain/employee/dto/response/EmployeeInfo.java
  src/main/java/com/toy4/domain/employee/dto/response/PersonalInfo.java
  src/main/java/com/toy4/domain/employee/service/EmployeeService.java
  src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java
  src/main/java/com/toy4/global/config/WebMvcConfig.java
  src/main/java/com/toy4/global/file/component/EmployeeProfileImageService.java
  src/main/resources/application.yml
  src/main/resources/static/images/default/user.png
  src/test/resources/application.yml
Labels: refactor

#105 feat: 로그 인터셉터 구현 및 설정 (#103)
  src/main/java/com/toy4/global/config/WebMvcConfig.java
  src/main/java/com/toy4/global/interceptor/LogInterceptor.java
Labels: feature

#117 fix: 연차 등록 거절 시 잔여 연차 수 복구 (#84)
  src/main/java/com/toy4/domain/dayOffHistory/service/impl/DayOffHistoryServiceImpl.java
Labels: fix

#121 대기중, 승인에 대한 조건절 추가
  src/main/java/com/toy4/domain/dayOffHistory/repository/info/DayOffHistoryCustomRepositoryImpl.java
  src/main/java/com/toy4/domain/employee/dto/response/EmployeeDayOffInfoResponse.java
Labels: fix

#123 fix: 메일에 첨부된 비밀번호 변경 URL 변경 (#122)
  src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java
Labels: fix

#129 대기중, 승인됨에 대한 조건 변경
  src/main/java/com/toy4/domain/dayOffHistory/repository/info/DayOffHistoryCustomRepositoryImpl.java
Labels: fix
